Add interceptor exception
conduktor/conduktor-gateway pull request #9
Opened 2023-04-06 22:23 UTC by vuduchailinh

Add exceptions for interceptor-framework:
- validate config,
- gateway-core can catch and return an errors response to the client

2023-04-07 08:41 UTC, manhcuongbk56 requested changes

2023-04-07 08:41 UTC, manhcuongbk56 commented on interceptor-framework/src/main/java/io/conduktor/gateway/interceptor/InterceptorIntentionException.java
> +public class InterceptorIntentionException extends RuntimeException{
Should not change name of this exception.

2023-04-07 13:50 UTC, vuduchailinh commented on interceptor-framework/src/main/java/io/conduktor/gateway/interceptor/InterceptorIntentionException.java
> +public class InterceptorIntentionException extends RuntimeException{
I moved this class from gateway-core to interceptor-framework, I think it needs to be renamed

2023-04-10 10:11 UTC, manhcuongbk56 approved these changes
LGTM

2023-04-11 07:38 UTC, merged